/**
 * POST /api/compliance/dpr
 *
 * Public endpoint — no auth required. Called by the DPR intake form at
 * /dpr-intake/[org_slug]. Creates a dpr_requests row using the service-role
 * client (bypasses RLS). SLA deadline is 30 days from submission.
 */
import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as {
      org_slug?: string
      principal_name?: string
      principal_email?: string
      request_type?: string
      description?: string
    }

    const { org_slug, principal_name, principal_email, request_type, description } = body

    if (!org_slug || !principal_name || !principal_email || !request_type || !description) {
      return NextResponse.json({ error: 'All fields are required' }, { status: 400 })
    }

    const validTypes = ['access', 'correction', 'erasure', 'nomination', 'grievance', 'portability']
    if (!validTypes.includes(request_type)) {
      return NextResponse.json({ error: 'Invalid request_type' }, { status: 400 })
    }

    const supabase = createAdminClient()

    // Look up org by slug or id
    const { data: org, error: orgErr } = await supabase
      .from('organizations')
      .select('id, name')
      .or(`slug.eq.${org_slug},id.eq.${org_slug}`)
      .single()

    if (orgErr || !org) {
      return NextResponse.json({ error: 'Organisation not found' }, { status: 404 })
    }

    const slaDeadline = new Date()
    slaDeadline.setDate(slaDeadline.getDate() + 30)

    // ticket_number is auto-generated by the DB trigger
    const { data: dpr, error: insertErr } = await supabase
      .from('dpr_requests')
      .insert({
        org_id:         org.id,
        ticket_number:  'PENDING', // trigger overwrites this
        principal_name: principal_name.trim(),
        principal_email: principal_email.trim().toLowerCase(),
        request_type:   request_type as 'access' | 'correction' | 'erasure' | 'nomination' | 'grievance' | 'portability',
        description:    description.trim(),
        sla_deadline:   slaDeadline.toISOString(),
      })
      .select('ticket_number')
      .single()

    if (insertErr || !dpr) {
      console.error('[dpr/POST] insert error:', insertErr)
      return NextResponse.json({ error: 'Failed to create request' }, { status: 500 })
    }

    // Best-effort email notification to org admins (gracefully degrades)
    try {
      if (process.env.RESEND_API_KEY) {
        const { data: admins } = await supabase
          .from('org_members')
          .select('users!user_id(email, full_name)')
          .eq('org_id', org.id)
          .in('role', ['admin'])
          .eq('status', 'active')
          .limit(3)

        const adminEmails = (admins ?? [])
          .flatMap((m) => {
            const u = (m as { users: { email: string } | { email: string }[] | null }).users
            return Array.isArray(u) ? u.map((x) => x.email) : u ? [u.email] : []
          })
          .filter(Boolean)

        if (adminEmails.length > 0) {
          await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              from: 'LexGuard Legal <noreply@lexguard.in>',
              to: adminEmails,
              subject: `New Data Principal Request — ${dpr.ticket_number}`,
              html: `<p>A new data principal rights request has been submitted via your DPR intake form.</p>
                     <p><strong>Ticket:</strong> ${dpr.ticket_number}<br>
                     <strong>Type:</strong> ${request_type}<br>
                     <strong>SLA Deadline:</strong> ${slaDeadline.toLocaleDateString('en-IN')}</p>
                     <p>Log in to LexGuard Legal to view and respond.</p>`,
            }),
          })
        }
      }
    } catch {
      // email failure is non-fatal
    }

    return NextResponse.json({ ticket_number: dpr.ticket_number })
  } catch (err) {
    console.error('[dpr/POST] unexpected error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
